sudo: false

language: php

branches:
  only:
    - master
    - develop

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=locked
        - CS_CHECK=true
        - TEST_COVERAGE=true
    - php: 7.2
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
        - CS_CHECK=true
    - php: 7.1
      env:
        - DEPS=latest
#    - php: 7
#      env:
#        - DEPS=lowest
#    - php: 7
#      env:
#        - DEPS=locked
#        - CS_CHECK=true
#    - php: 7
#      env:
#        - DEPS=latest
#    - php: 5.6
#      env:
#        - DEPS=lowest
#    - php: 5.6
#      env:
#        - DEPS=locked
#        - CS_CHECK=true
#    - php: 5.6
#      env:
#        - DEPS=latest

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

before_install:
  - travis_retry composer self-update
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
